### ISSUE TITLE
Inject bug

### ISSUE THREAD

**Issue by hugocarreira** [johnpapa/vscode-angular1-snippets#17]
Hi @johnpapa 

Firstly, thanks for your contributions, both the guide and these snippets, they are wonderfull ;)

So, I'm having problems in snippets, when used the variable inject is populated without the $.

Ex: `controler.inject = ['..'];`

I tried to fix but I did not succeed because this bug stay in VSCode Marketplace, not here.

**Comment by johnpapa** [comment]
Is this fixed now for you?

**Comment by hugocarreira** [comment]
I fixed in my machine, but in vscode marketplace is still with bug
