### ISSUE TITLE
Please update version on vscode market

### ISSUE THREAD

**Issue by DrakeXiang** [johnpapa/vscode-angular1-snippets#18]
There are some annoying bugs of current version on the market, please fix and publish, thanks.

**Comment by johnpapa** [comment]
can you explain the bugs so I can fix them, please?

thanks

**Comment by DrakeXiang** [comment]
@johnpapa Thanks for getting back, the main issue was missing dollar sign ($) as stated [here](https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular1), but I see you updated the extension on vscode recently, seems working fine to me now :) thanks
